#!/usr/bin/env bash
# =============================================================================
# Hippocampus Pipeline – Linux / macOS Startup Script
# =============================================================================
#
# What this does:
#   1. Mounts the host root filesystem (/) into the backend container
#   2. Generates docker-compose.override.yml
#   3. Starts the Docker containers
#
# Usage:
#   ./start.sh                # build & start
#   ./start.sh --no-build     # start without rebuilding
#   ./start.sh --stop         # stop containers
#
# =============================================================================

set -e

# ── Parse args ────────────────────────────────────────────────────────
NO_BUILD=false
STOP=false

for arg in "$@"; do
    case "$arg" in
        --no-build) NO_BUILD=true ;;
        --stop)     STOP=true ;;
        --help|-h)
            cat <<EOF

  Hippocampus Pipeline – Startup Script (Linux / macOS)

  Usage:
    ./start.sh                Build and start the pipeline
    ./start.sh --no-build     Start without rebuilding images
    ./start.sh --stop         Stop all containers

  The script mounts your root filesystem (/) into the backend
  container so you can browse your entire filesystem from the
  web UI at http://localhost:3000/dataset

EOF
            exit 0
            ;;
    esac
done

# ── Stop ──────────────────────────────────────────────────────────────
if [ "$STOP" = true ]; then
    echo "Stopping containers..."
    docker compose down
    exit 0
fi

# ── Banner ────────────────────────────────────────────────────────────
echo ""
echo "  Hippocampus Radiomic Feature Extraction Pipeline"
echo "  ================================================"
echo ""

# ── Generate docker-compose.override.yml ──────────────────────────────
echo "Mounting host filesystem (/) -> /host/root ..."

cat > docker-compose.override.yml <<'EOF'
# =============================================================================
# AUTO-GENERATED by start.sh – DO NOT EDIT
# Regenerated every time you run ./start.sh
# =============================================================================

services:
  backend:
    volumes:
      - /:/host/root
EOF

echo "Generated docker-compose.override.yml"
echo ""

# ── Start containers ──────────────────────────────────────────────────
if [ "$NO_BUILD" = true ]; then
    echo "Starting containers..."
    docker compose up -d
else
    echo "Building and starting containers..."
    docker compose up --build -d
fi

echo ""
echo "  Pipeline is running!"
echo "  Frontend:  http://localhost:3000"
echo "  Backend:   http://localhost:5000"
echo "  Dataset:   http://localhost:3000/dataset"
echo ""
echo "  Stop with:  ./start.sh --stop"
echo ""
