#!/usr/bin/env pwsh
# =============================================================================
# Hippocampus Pipeline – Windows Startup Script
# =============================================================================
#
# What this does:
#   1. Detects all available drives on your system (C:, D:, E:, ...)
#   2. Generates docker-compose.override.yml with volume mounts for each drive
#   3. Starts the Docker containers
#
# Usage:
#   .\start.ps1              # build & start
#   .\start.ps1 -NoBuild     # start without rebuilding
#   .\start.ps1 -Stop        # stop containers
#
# =============================================================================

param(
    [switch]$NoBuild,
    [switch]$Stop,
    [switch]$Help
)

if ($Help) {
    Write-Host @"

  Hippocampus Pipeline – Startup Script (Windows)

  Usage:
    .\start.ps1              Build and start the pipeline
    .\start.ps1 -NoBuild     Start without rebuilding images
    .\start.ps1 -Stop        Stop all containers

  The script auto-detects all available drives and mounts them
  into the backend container so you can browse your entire
  filesystem from the web UI at http://localhost:3000/dataset

"@
    exit 0
}

# ── Stop ──────────────────────────────────────────────────────────────
if ($Stop) {
    Write-Host "Stopping containers..." -ForegroundColor Yellow
    docker compose down
    exit 0
}

# ── Detect drives ─────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Hippocampus Radiomic Feature Extraction Pipeline" -ForegroundColor Cyan
Write-Host "  ================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Detecting drives..." -ForegroundColor Yellow

$drives = Get-PSDrive -PSProvider FileSystem |
    Where-Object { $_.Root -match '^[A-Za-z]:\\$' } |
    Sort-Object Name

if ($drives.Count -eq 0) {
    Write-Host "ERROR: No filesystem drives detected!" -ForegroundColor Red
    exit 1
}

# ── Generate docker-compose.override.yml ──────────────────────────────
$volumeLines = @()
foreach ($d in $drives) {
    $letter = $d.Name.ToLower()
    $root = $d.Root  # e.g. "C:\"
    $volumeLines += "      - ${root}:/host/${letter}"
    Write-Host "  Drive $($d.Name): -> /host/$letter" -ForegroundColor Green
}

$override = @"
# =============================================================================
# AUTO-GENERATED by start.ps1 – DO NOT EDIT
# Regenerated every time you run .\start.ps1
# =============================================================================

services:
  backend:
    volumes:
$($volumeLines -join "`n")
"@

$override | Out-File -FilePath "docker-compose.override.yml" -Encoding UTF8 -Force
Write-Host ""
Write-Host "Generated docker-compose.override.yml with $($drives.Count) drive(s)" -ForegroundColor Green
Write-Host ""

# ── Start containers ──────────────────────────────────────────────────
if ($NoBuild) {
    Write-Host "Starting containers..." -ForegroundColor Yellow
    docker compose up -d
} else {
    Write-Host "Building and starting containers..." -ForegroundColor Yellow
    docker compose up --build -d
}

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "  Pipeline is running!" -ForegroundColor Green
    Write-Host "  Frontend:  http://localhost:3000" -ForegroundColor Cyan
    Write-Host "  Backend:   http://localhost:5000" -ForegroundColor Cyan
    Write-Host "  Dataset:   http://localhost:3000/dataset" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Stop with:  .\start.ps1 -Stop" -ForegroundColor DarkGray
    Write-Host ""
} else {
    Write-Host "ERROR: Docker Compose failed to start." -ForegroundColor Red
    exit 1
}
